apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
      app: pulp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
      name: httpd

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  template:
    metadata:
      labels:
          app: pulp
          name: httpd
    spec:
        containers:
            - name: httpd
              image: pulp/httpd
              imagePullPolicy: Never
              ports:
                  - containerPort: 80
                  - containerPort: 443
              volumeMounts:
                  - name: pulp-config
                    mountPath: /mnt/pulp-config/
                    readOnly: true
                  - name: httpd-cert
                    mountPath: /mnt/httpd-cert/
                    readOnly: true
                  - name: vlp
                    mountPath: /var/lib/pulp/
                  - name: logvol
                    mountPath: /dev/log
                    readOnly: false
        volumes:
            - name: pulp-config
              secret:
                  secretName: pulp-config
            - name: httpd-cert
              secret:
                  secretName: httpd-cert
            - name: vlp
              persistentVolumeClaim:
                  claimName: vlp
            - name: logvol
              hostPath:
                  path: /dev/log
