apiVersion: v1
kind: Pod
metadata:
  name: manage
  labels:
    app: pulp
spec:
  restartPolicy: Never
  containers:
    - name: manage
      image: pulp/manage
      imagePullPolicy: Never
      volumeMounts:
        - name: pulp-config
          mountPath: /mnt/pulp-config/
          readOnly: true
        - name: logvol
          mountPath: /dev/log
          readOnly: false
        - name: vlp
          mountPath: /var/lib/pulp/
  volumes:
    - name: pulp-config
      secret:
        secretName: pulp-config
    - name: logvol
      hostPath:
          path: /dev/log
    - name: vlp
      persistentVolumeClaim:
          claimName: vlp
