apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
      app: pulp
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
  selector:
      name: mongodb

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
          app: pulp
          name: mongodb
    spec:
        containers:
            - name: mongodb
              image: pulp/mongodb
              imagePullPolicy: Never
              ports:
                  - containerPort: 27017
