apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resource-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
          app: pulp
          name: resource-manager
    spec:
        containers:
            - name: resource-manager
              image: pulp/celery
              imagePullPolicy: Never
              args:
                  - resource_manager
              volumeMounts:
                  - name: pulp-config
                    mountPath: /mnt/pulp-config/
                    readOnly: true
                  - name: client-cert
                    mountPath: /mnt/client-cert/
                    readOnly: true
                  - name: pulp-ca
                    mountPath: /mnt/pulp-ca/
                  - name: vlp
                    mountPath: /var/lib/pulp/
                  - name: logvol
                    mountPath: /dev/log
                    readOnly: false
        volumes:
            - name: pulp-config
              secret:
                  secretName: pulp-config
            - name: client-cert
              secret:
                secretName: client-cert
            - name: pulp-ca
              configMap:
                  name: pulp-ca
            - name: vlp
              persistentVolumeClaim:
                  claimName: vlp
            - name: logvol
              hostPath:
                  path: /dev/log
