apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
      app: pulp
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
  selector:
      name: mongodb

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
          app: pulp
          name: mongodb
    spec:
        containers:
            - name: mongodb
              image: pulp/mongodb
              imagePullPolicy: Never
              ports:
                  - containerPort: 27017
              volumeMounts:
                  - name: mongodb-cert
                    mountPath: /var/run/secrets/pulp/mongodb-cert/
                    readOnly: true
                  - name: pulp-ca
                    mountPath: /var/run/secrets/pulp/pulp-ca/
                  - name: vlm
                    mountPath: /var/lib/mongodb/
        volumes:
            - name: mongodb-cert
              secret:
                  secretName: mongodb-cert
            - name: pulp-ca
              configMap:
                  name: pulp-ca
            - name: vlm
              persistentVolumeClaim:
                  claimName: vlm
